### ISSUE TITLE
Jump 

### ISSUE THREAD

**Issue by Istanful** [Istanful/Ett-spel#3]
**Short intro**
Make the character jump by holding the left side of the screen.

**Long intro**
A needed feature in the game. When you tap the left side of the screen the character will jump. I was once thinking about having it trigger to the first tap left to the last tap but that would just be retarded. Zone of the screen from the middle so that right part is aiming and left part is jumping. Keep in mind that we will maybe want some power buttons like in LoL in a later version. The character should jump as high as an imp and a little more. Hold to jump higher.

**Tasks:**
- [ ] Fix jump animation spritesheet
- [ ] Fix jump sounds
  - [x] For jump with clothy clothes
  - [x] Tree land
  - [ ] Grass land
- [ ] Fix jump code
  - [ ] Make it jump
  - [ ] Make it hold
